name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run:  |
          sudo apt-get update
          sudo apt-get install -y cowsay
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt