name: Vehicle Server CI
on:
  - push
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.x'
      - name: Check Node Version
        run: node --version
      - name: Build application
        run: npm run build
      - name: List dist output
        run: ls dist/